---
title: "Weight of Fish"
author: "Ezra Licciardi"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
require(car)
require(leaps)
```

# Predicting Fish Weight
```{r}
fish <- read.csv(file = "Fish.csv")
```

```{r eval=TRUE}
 
fish <- fish %>%
mutate(across(where(is.character), as.factor))
levels(fish$Species)
Bream <- filter(fish, Species == "Bream")
Bream <- select(Bream, -Species) 
Parkki <- filter(fish, Species == "Parkki")
Parkki <- select(Parkki, -Species) 
Perch <- filter(fish, Species == "Perch")
Perch <- select(Perch, -Species) 
Pike <- filter(fish, Species == "Pike")
Pike <- select(Pike, -Species) 
Roach <- filter(fish, Species == "Roach")
Roach <- select(Roach, -Species) 
Smelt <- filter(fish, Species == "Smelt")
Smelt <- select(Smelt, -Species) 
Whitefish <- filter(fish, Species == "Whitefish")
Whitefish <- select(Whitefish, -Species) 
```

# For each of the three species of fish listed below, determine the best regression model and also the best 2 element regression model. Use the BestSubset Regression helper file.


## Perch
```{r}

Perch1 <- lm(Weight~ .,data=Perch)
summary.lm(Perch1)
Perch1 <- lm(Weight~ .-Length1,data=Perch)
summary.lm(Perch1)
Perch1 <- lm(Weight~ .-Length1-Length2,data=Perch)
summary.lm(Perch1)
Perch1 <- lm(Weight~ .-Length1-Length2-Width,data=Perch)
summary.lm(Perch1)
#model2 <- lm(___~___,data=mydata)
#model3 <- lm(___~___,data=mydata)
#target1 <- data.frame()

```
### Best Models

### Best Two regressor model


## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements